import type { Metadata } from "next";
import "./globals.css";
import { ProgressBar } from "@/context/ProgressBar";
import AuthProvider from "@/context/AuthProvider";
import ThemeProvider from "@/context/ThemeProvider";


export const metadata: Metadata = {
  title: "Shop Seva",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
          <ThemeProvider>
            <AuthProvider>
              <ProgressBar className="h-1 bg-navigation">{children}</ProgressBar>
            </AuthProvider>
          </ThemeProvider>
    </html>
  );
}
