import type { Metadata } from "next";
import "./globals.css";
import { ProgressBar } from "@/context/ProgressBar";
import AuthProvider from "@/context/AuthProvider";
import ThemeProvider from "@/context/ThemeProvider";
import { cookies } from "next/headers";
import { apiClient } from "@/lib/apiClient";

export const metadata: Metadata = {
  title: "Shop Seva",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let user = null;
  try {
    const cookie = await cookies();
    const token = cookie.get("accessToken")?.value || null;
    if (token) {
      const { data } = await apiClient.get(
        "http://localhost:3000/api/auth/verify-token?token=" + token
      );
      if (data) {
        user = data.user;
      }
    }
  } catch (err) {
    if (err) {
      user = null;
    }
  }

  return (
    <html lang="en">
      <ThemeProvider>
        <AuthProvider initialValue={user}>
          <ProgressBar className="h-1 bg-navigation">{children}</ProgressBar>
        </AuthProvider>
      </ThemeProvider>
    </html>
  );
}
